In [1]:
import pandas as pd
import re
import string

In [2]:
df = pd.read_csv("sentiment.csv",
                 header=None,
                 names=["ID", "Entity", "Sentiment", "Text"])

In [3]:
df.shape

(74682, 4)

In [4]:
df.head(5)

,ID,Entity,Sentiment,Text
0,2401,Borderlands,Positive,im getting on borderlands and i will murder yo...
1,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
2,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
3,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
4,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...

In [5]:
df.sample(10)

,ID,Entity,Sentiment,Text
52789,10669,RedDeadRedemption(RDR),Irrelevant,Can't trust the mfs who played red all the tim...
6966,399,Amazon,Negative,............ Please don't fuck this up.
56474,11291,TomClancysRainbowSix,Neutral,"@ Rainbow6Game First of all, I love this game...."
26802,1006,AssassinsCreed,Neutral,The Order: 1886. Assassin's Creed Liberation. ...
17295,9765,PlayStation5(PS5),Positive,"It came appealing, can't deny that."
50550,6277,FIFA,Positive,Premier League celebrating the early launch of...
43848,10329,PlayerUnknownsBattlegrounds(PUBG),Irrelevant,"It's toga's birthdayyyyyayaya, the way I love ..."
9187,9579,Overwatch,Negative,My most embarrassing Overwatch moment pic.twit...
7599,9306,Overwatch,Negative,@PlayOverwatch coming back to overwatch after ...
41772,1568,Battlefield,Irrelevant,EA is permanently banning Linux players on Bat...

In [6]:
df.isnull().sum()

ID             0
Entity         0
Sentiment      0
Text         686
dtype: int64

In [7]:
df.dtypes

ID            int64
Entity       object
Sentiment    object
Text         object
dtype: object

In [8]:
df.value_counts()

ID     Entity                             Sentiment   Text
3018   Dota2                              Positive    Wow.                                                                                                                               5
4050   CS-GO                              Positive    Wow                                                                                                                                5
10181  PlayerUnknownsBattlegrounds(PUBG)  Irrelevant  Really                                                                                                                             5
8808   Nvidia                             Positive    Wow                                                                                                                                5
6928   johnson&johnson                    Negative    "                                                                                                                                  5
                                                                                                                                                                                        ..
4339   CS-GO                              Negative    @ CSGO Your "official servers" are a hotbed for hackers...... @ valvesoftware pls fix.                                             1
                                                      @ CSGO your "official servers" are a breeding ground for fraudsters...... @ valvesopls.                                            1
                                                      @CSGO your "official servers" are a breeding zone for hackers.. .. .. @valvesoftware pls fix.                                      1
                                                      @CSGO your "official servers" are a happy zone for spam.... @valvesoftware pls fix.                                                1
13200  Xbox(Xseries)                      Irrelevant  More Amazing deal I found out on ebay looked for quite a RAZER HEADSET.. See rover. net ebay. com / rover / 1 / 08 710 - 53 …..    1
Name: count, Length: 71656, dtype: int64

In [9]:
df.duplicated().sum()

np.int64(2700)

In [10]:
df.shape

(74682, 4)

In [11]:
df.dropna(inplace=True)

In [12]:
df.shape

(73996, 4)

In [13]:
df["Sentiment"].value_counts()

Sentiment
Negative      22358
Positive      20655
Neutral       18108
Irrelevant    12875
Name: count, dtype: int64

In [14]:
df = df[df["Sentiment"] != "Irrelevant"]

In [15]:
df["Sentiment"].value_counts()

Sentiment
Negative    22358
Positive    20655
Neutral     18108
Name: count, dtype: int64

In [16]:
df.shape

(61121, 4)

In [17]:
df.drop_duplicates(inplace=True)

In [18]:
df.shape

(59119, 4)

In [19]:
df["Text"] = df["Text"].str.lower()

In [20]:
df.sample

<bound method NDFrame.sample of          ID       Entity Sentiment  \
0      2401  Borderlands  Positive
1      2401  Borderlands  Positive
2      2401  Borderlands  Positive
3      2401  Borderlands  Positive
4      2401  Borderlands  Positive
...     ...          ...       ...
74677  9200       Nvidia  Positive
74678  9200       Nvidia  Positive
74679  9200       Nvidia  Positive
74680  9200       Nvidia  Positive
74681  9200       Nvidia  Positive

                                                    Text
0      im getting on borderlands and i will murder yo...
1      i am coming to the borders and i will kill you...
2      im getting on borderlands and i will kill you ...
3      im coming on borderlands and i will murder you...
4      im getting on borderlands 2 and i will murder ...
...                                                  ...
74677  just realized that the windows partition of my...
74678  just realized that my mac window partition is ...
74679  just realized the windows partition of my mac ...
74680  just realized between the windows partition of...
74681  just like the windows partition of my mac is l...

[59119 rows x 4 columns]>

In [21]:
def remove_urls(text):
    return re.sub(r'http\S+|www\S+', '', text)

In [22]:
df["Text"] = df["Text"].apply(remove_urls)

In [23]:
df.head

<bound method NDFrame.head of          ID       Entity Sentiment  \
0      2401  Borderlands  Positive
1      2401  Borderlands  Positive
2      2401  Borderlands  Positive
3      2401  Borderlands  Positive
4      2401  Borderlands  Positive
...     ...          ...       ...
74677  9200       Nvidia  Positive
74678  9200       Nvidia  Positive
74679  9200       Nvidia  Positive
74680  9200       Nvidia  Positive
74681  9200       Nvidia  Positive

                                                    Text
0      im getting on borderlands and i will murder yo...
1      i am coming to the borders and i will kill you...
2      im getting on borderlands and i will kill you ...
3      im coming on borderlands and i will murder you...
4      im getting on borderlands 2 and i will murder ...
...                                                  ...
74677  just realized that the windows partition of my...
74678  just realized that my mac window partition is ...
74679  just realized the windows partition of my mac ...
74680  just realized between the windows partition of...
74681  just like the windows partition of my mac is l...

[59119 rows x 4 columns]>

In [24]:
df[df["Text"].str.contains("@", na=False)].head()

,ID,Entity,Sentiment,Text
6,2402,Borderlands,Positive,so i spent a few hours making something for fu...
7,2402,Borderlands,Positive,so i spent a couple of hours doing something f...
8,2402,Borderlands,Positive,so i spent a few hours doing something for fun...
30,2406,Borderlands,Positive,we finished borderlands 3 finally yas! thank y...
31,2406,Borderlands,Positive,we finally finally find borderlands 3 yes! tha...

In [25]:
def remove_mentions(text):
    text = re.sub(r'@\s*\S+', '', text)
    text = re.sub(r'@', '', text)   
    return text

In [26]:
df["Text"] = df["Text"].apply(remove_mentions)

In [27]:
df["Text"]

0        im getting on borderlands and i will murder yo...
1        i am coming to the borders and i will kill you...
2        im getting on borderlands and i will kill you ...
3        im coming on borderlands and i will murder you...
4        im getting on borderlands 2 and i will murder ...
                               ...
74677    just realized that the windows partition of my...
74678    just realized that my mac window partition is ...
74679    just realized the windows partition of my mac ...
74680    just realized between the windows partition of...
74681    just like the windows partition of my mac is l...
Name: Text, Length: 59119, dtype: object

In [28]:
df[df["Text"].str.contains("@", na=False)].head()

Empty DataFrame
Columns: [ID, Entity, Sentiment, Text]
Index: []

In [29]:
def remove_hashtags(text):
    return re.sub(r'#', '', text)

df["Text"] = df["Text"].apply(remove_hashtags)

In [30]:
df[df["Text"].str.contains("#", na=False)].head()

Empty DataFrame
Columns: [ID, Entity, Sentiment, Text]
Index: []

In [31]:
def remove_punctuations(text):
    return text.translate(str.maketrans('', '', string.punctuation))

In [32]:
df["Text"] = df["Text"].apply(remove_punctuations)

In [33]:
df["Text"].head(10)

0    im getting on borderlands and i will murder yo...
1    i am coming to the borders and i will kill you...
2    im getting on borderlands and i will kill you all
3    im coming on borderlands and i will murder you...
4    im getting on borderlands 2 and i will murder ...
5    im getting into borderlands and i can murder y...
6    so i spent a few hours making something for fu...
7    so i spent a couple of hours doing something f...
8    so i spent a few hours doing something for fun...
9    so i spent a few hours making something for fu...
Name: Text, dtype: object

In [34]:
def extra_spaces(text):
    text = " ".join(text.split())
    return text

In [35]:
df["Text"] = df["Text"].apply(extra_spaces)

In [36]:
df["Text"].head(10)

0    im getting on borderlands and i will murder yo...
1    i am coming to the borders and i will kill you...
2    im getting on borderlands and i will kill you all
3    im coming on borderlands and i will murder you...
4    im getting on borderlands 2 and i will murder ...
5    im getting into borderlands and i can murder y...
6    so i spent a few hours making something for fu...
7    so i spent a couple of hours doing something f...
8    so i spent a few hours doing something for fun...
9    so i spent a few hours making something for fu...
Name: Text, dtype: object

In [37]:
df.isnull().sum()

ID           0
Entity       0
Sentiment    0
Text         0
dtype: int64

In [38]:
df.to_csv("cleaned_sentiment.csv", index=False)